### ISSUE TITLE
ActivityTypeCode - create function to deal with replicates

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#102]
Example: 
The ActivityTypeCode field has four unique values -- "Sample-Routine", "Quality Control Sample-Field Replicate", "Field Msr/Obs", and "Quality Control Sample-Field Blank." In this example we want to remove quality control values in the ActivityTypeCode field, therefore, we'll specify that we want to remove the "Quality Control Sample-Field Replicate" and "Quality Control Sample-Field Blank" values in the ActivityTypeCode field.
```{r}
TADAProfileClean13 <- dplyr::filter(TADAProfileClean12, !(ActivityTypeCode %in% c("Quality Control Sample-Field Replicate", "Quality Control Sample-Field Blank")))
```

COMMENT from Christy Meredith MT DEQ; other options besides removing replicates that we sometimes use is to average the replicates with the samples they are matched with ,or to randomly select one of the replicates. Sometimes we do not use the data if the replicate is not within a certain range of the other value.  Not sure if some of this functionality could eventually be added as an option? Or would this be done outside of TADA?

**Comment by cristinamullin** [comment]
See: https://github.com/USEPA/TADA/issues/213

**Comment by ehinman** [comment]
I've been thinking about this a little bit after creating a new function for finding potential QC duplicates/replicates within organizations. It seems like we may want to create another function that identifies Routine Sample - QC Sample pairings, using similar logic to these ID duplicate results between/within orgs (though not similar enough to combine). The two different ways I can see this function looking for QC samples is:
1. Group data by org, site, date, characteristic, fraction....maybe others.... and look for situations where more than one result is returned, and one of them has a QC-like activity-type code. This could define a QC Sample group.
2. Group data by org, date, characteristic, fraction...maybe others...and use the identify nearby sites function to find groups of sites where one or more sites within the group have the words "duplicate" or "replicate" in the monitoring location name or ID.
The function could try both and catch what it can. Cristina also sent this (from Kevin):
WQX data submitters can use the ActivityIdentifierUserSupplied for this purpose of matching samples (parent) with their associated replicate, or for matching up lab duplicates (i.e., parent grouping). It can also be used in another way, for data submitters to include their own internal activity ID that might be different from the one used for WQX.

The other element, ActivityGroupTypes, can be used to group Activities that have different ActivityTypeCodes together more easily… for example to group field sets with associated QC Samples, Replicates, Subsamples, etc. from the same trip/activity. I could see this being useful for matching a hardness result with a metal result, for use of the “paired” data in a equation based metals criteria analysis.

**Comment by katiehealy** [comment]
I like the idea of trying both! I think I remember seeing an example where the site name for the replicate was slightly different than the site name for the "parent" sample (i.e. Site1 and Site1-Replicate). That's where I was thinking of using the lat/longs to identify replicate sites - which is where your identify-nearby-sites function could fit in, but I maybe misunderstood what that function's intention was. I'll try to play around with these ideas on Friday!

**Comment by ehinman** [comment]
Yeah! I think the TADA_FindNearbySites could totally be used in this process, I may have ALSO misunderstood during the working group meeting. TADA_FindNearbySites groups sites together based on distance but doesn't do anything in the way of identifying duplicates, so would make sense to use to identify duplicate/replicate sites.
