### ISSUE TITLE
Add examples to documentation

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#126]
https://r-pkgs.org/man.html#sec-man-examples

See relevant comments here: https://github.com/USEPA/TADA/pull/121
- “I'd highly recommend adding more examples to all the functions. These will get tested as the package is checked. Also, they get run and the output is displayed in the pkgdown output. I'm a huge fan of lots of examples.”

Also, see example in DataDiscoveryRetrieval.R documentation.
- Note: Add \donttest to any example that makes an internet call. If your function is just doing something local, you don't need the donttest.

**Comment by cristinamullin** [comment]
Update: \donttest doesn't pass the check() anymore with current R updates. Trying \dontrun instead for now, but note this will not pass CRAN tests when submitting for the first time.

**Comment by cristinamullin** [comment]
@katiehealy do you think this issue be closed now, or are there places we might still want to add additional documentation? Thanks!

**Comment by katiehealy** [comment]
I added examples and documentation to functions in:
- ResultFlagsDependent.R, 
- ResultFlagsIndependent.R, 
- Transformations.R (except HarmonizeCensoredData() and CensoredDataStats()), and 
- Filtering.R, 
There are more places we could add documentation. Here are some lacking documentation still:
- GenerateRefTables.R (I'd need someone to explain some of these functions to me before I could add documentation)
- IdentifyPotentialDuplicates.R (doesn't have examples)
- Utilities (doesn't have examples)
- Censored Data Suite (doesn't have examples)
