### ISSUE TITLE
HarmonizationRefTable and HarmonizeData

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#131]
Users are reporting that these are not running, and they are getting the following error: 
“Error in `[.data.frame`(flag.data, , col.order) :  undefined columns selected”

I believe this has been resolved and they may simply need to pull the current version of TADA, but I'm not sure. 

Shelly and Laura, if you could test these two (they are at the end of the vignette), that would be greatly appreciated!

**Comment by cristinamullin** [comment]
Edited HarmonizeData to always run HarmonizationRefTable first on the reference file so it only includes combinations relevant to the input dataset. This will help ensure consistency between a user supplied or default ref file too. 

The functions run, but the logic needs a little more tweaking. Need to review HarmonizationRefTable output in comparison with the reference harmonization file & write tests.

**Comment by ehinman** [comment]
@cristinamullin I'm not getting this error when I run these functions. Close for now?
