### ISSUE TITLE
DepthProfileData function ConversionFactor output column missing when no NaN in input column

### ISSUE THREAD

**Issue by jbousquin** [USEPA/TADA#137]
When trying to write tests for DepthProfileData function in [ResultFlagsDependent](https://github.com/USEPA/TADA/blob/develop/R/ResultFlagsDependent.R) I was getting the error:
```r
Error in `[.data.frame`(check.data, , col.order) : undefined columns selected
```
This happens on line [530](https://github.com/USEPA/TADA/blob/b5712d9bf54d9da0ac2900469a75517aee39f5fe/R/ResultFlagsDependent.R#L530) because the column order list includes columns that don't exist in check.data. This may also relate to [issue #131](https://github.com/USEPA/TADA/issues/131).

In my case the missing column was derived from 'ActivityDepthHeightMeasure.MeasureUnitCode' which had units and no NaN. If the column is in fields (I was using the default) the if statement on line [404](https://github.com/jbousquin/TADA/blob/b5712d9bf54d9da0ac2900469a75517aee39f5fe/R/ResultFlagsDependent.R#L404) appears to catch and continue when there are more than 0 NaN in the column. Based on the comment on the line above I think the inverse was intended (i.e., continue if more than 0 are NOT NaN):
```r
if (sum(!is.na(check.data$ActivityDepthHeightMeasure.MeasureUnitCode)) > 0)  {
```
Wanted to make sure I understood the intended logic correctly before submitting a PR.

**Comment by cristinamullin** [comment]
Hey Justin, you're correct, the inverse was intended (i.e., continue if more than 0 are NOT NaN). Thank you so much for catching this!

**Comment by cristinamullin** [comment]
reverted this change for now due to check() issues. Need to troubleshoot

**Comment by jbousquin** [comment]
Yeah - not sure why checks passed on the PR but then failed after it was merged.

This change does cause additional downstream issues that I've resolved (see [commit](https://github.com/USEPA/TADA/commit/f01ecbe528160dfa378bfbee86f092d4cae802d7)) but those shouldn't be causing checks to fail. Will see if I can get it passing checks again before submitting.

**Comment by cristinamullin** [comment]
I just submitted my changes to the harmonize functions & a few other patches. It's all passing check() now. Can you pull the current changes & merge on your end before submitting? Hopefully it'll work now with your downstream changes too - thanks so much again for your contributions!
