### ISSUE TITLE
R Shiny flag page prerequisites

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#140]
Review the following functions to prepare for R Shiny flag page development
•	[RemoveEmptyColumns()](https://usepa.github.io/TADA/reference/RemoveEmptyColumns.html)
•	[InvalidCoordinates()](https://usepa.github.io/TADA/reference/InvalidCoordinates.html)
•	[QAPPapproved()](https://usepa.github.io/TADA/reference/QAPPapproved.html)
•	[DepthProfileData()](https://usepa.github.io/TADA/reference/DepthProfileData.html)

**Comment by ehinman** [comment]
RemoveEmptyColumns seems fine as long as someone doesn't accidentally remove a column needed to make decisions later on in the process. What are the core columns needed to go from start to finish in TADAShiny? It seems like that list should be in this function, and if ALL records are NA for a required column, perhaps this function should throw a warning/alert.

**Comment by ehinman** [comment]
Regarding InvalidCoordinates: What is the basis for removing lat/longs with fewer than 3 decimal digits? A test dataset I ran through it flagged a lot of USGS sites that didn't necessarily seem erroneous, but perhaps did land in the vicinity of ##.##000? How do we know less than 3 digits is imprecise vs ending in 0000...?
