### ISSUE TITLE
address symbols “<” in depth fields

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#150]
Roop pointed out that "if there are “<” in and of the depth fields, they delete the “<”. Usually these show up when there are depth profiles." 

Need to find/create examples of this and add the logic to either the autoclean or convertdepthunits functions.

e.g., note from Jake: Edit entire function to make depth measure value fields permanently numeric. Currently the function creates a numeric copy of each field for calculations and then deletes the numeric copy (with coerced to NA warnings suppressed). It will be different from the MeasureValueSpecialCharacters function, but the code may be a helpful guide in updating the DepthProfileData function

**Comment by cristinamullin** [comment]
@ehinman does the new MeasureValueSpecialCharacters function you wrote cover this issue?

**Comment by ehinman** [comment]
Yes, it should, since it works on any column.
