### ISSUE TITLE
Checks for cols in colnames 2x

### ISSUE THREAD

**Issue by jbousquin** [USEPA/TADA#151]
In many of the functions in Transformations a stop error occurs if expected_cols in .data == FALSE, and then the main function occurs on the conditional that this is TRUE. I wouldn't expect this to change, is it adequate to just check the first time? If not could these be combined, i.e., if FALSE stop() else {continue function}?

**Comment by cristinamullin** [comment]
Yes I agree it looks like this bit of code is repetitive

**Comment by cristinamullin** [comment]
I can try to clean this up & maybe tackle this issue at the same time: https://github.com/USEPA/TADA/issues/95

I probably won't get to this for a few weeks though. If you have time and are interested feel free to make the changes. Thanks for submitting the issue!

**Comment by jbousquin** [comment]
Easy enough fix and I have it on a branch already - I think structuring as a check makes it more uniform with others and better transitions into a generalized solution (i.e. [issue #152 ](https://github.com/USEPA/TADA/issues/152)).
