### ISSUE TITLE
MeasureValueSpecialCharacters

### ISSUE THREAD

**Issue by jakegreif** [USEPA/TADA#17]
### Page Requirements/Standards
All of the flag page functions should be consistent in the following ways:
- Clean argument indicates whether flag columns should be appended to the data (clean = FALSE), or flagged data is transformed/filtered from the dataset and no columns are appended (clean = TRUE).
- Default is clean = FALSE

### Function Requirements
- Reference table required?
No
- Include warning if flags are not applied?
Yes, "Data summaries and calculations may be affected by choosing to retain special characters in the ResultValue field. In order to ensure transformation functions will run properly, set clean = TRUE."
- Required columns:
ResultMeasureValue

### Development Notes
ResultFlagsDependent.R

**Comment by jakegreif** [comment]
> scientific notation and issue with certain decimal numbers:
> 
> ![643a497a-60b2-490d-89cb-a1619565f94b](https://user-images.githubusercontent.com/46969696/167931441-426ac8da-48ad-4e85-9e1e-a809c891cc85.jpg) ![76d7b824-9ecb-403f-b151-435fb0c54b9f](https://user-images.githubusercontent.com/46969696/167931461-0eca531f-4f75-4913-834d-be4d3a6570a2.jpg)

I don't have time to try this, but consider looking into how to check for the letter 'e' after a numeric character and flag as 'Scientific Notation'.

**Comment by cristinamullin** [comment]
# make sure the following censoring information is retained
nitrogen <-
  nitrogen %>% mutate(ResultComment=
                        case_when(grepl("<", Result) ~ "<",
                                  grepl(">", Result) ~ ">",
                                  grepl("BDL", Result) ~ "<",
                                  grepl("bdl", Result) ~ "<",
                                  grepl("below detection limits", Result) ~ "<",
                                  grepl("Not Detected", ResultDetectionConditionText) ~ "<",
                                  grepl("Present Below Quantification Limit",  ResultDetectionConditionText) ~ "<"))

**Comment by cristinamullin** [comment]
add the following for both result and depth fields

  # convert missing value strings ("", " ", "<Blank>") to NA
    mutate(across(where(is.character), ~ na_if(.,""))) %>%
    mutate(across(where(is.character), ~ na_if(.," "))) %>%
    mutate(across(where(is.character), ~ na_if(.,"<Blank>")))

**Comment by cristinamullin** [comment]
@ehinman I wanted to flag this issue as well since it is about the MeasureValueSpecialCharacters function, which will impact the new censored data functions too

**Comment by ehinman** [comment]
Do you want to consider percentages for conversion to numeric? e.g. 50% becomes 50 and the flag is "Percentage"? I noticed in this query, nearly all of the result measures are from a "choice list" that is clearly percentages:
`
tada3 <- TADABigdataRetrieval(characteristicName = "Algae, substrate rock/bank cover (choice list)",
                              siteType = "Stream")
tada3 = ConvertSpecialChars(tada3, "ResultMeasureValue")
`
I'm not sure how prevalent percentages are in WQ assessment data, but if the aim is to squeeze as much as we can out of each record, this might be another way to make more data usable quantitatively.

**Comment by cristinamullin** [comment]
What is the unit supplied in this case? Can we simply remove the % from the result value and add that as a unit?

**Comment by ehinman** [comment]
When I've seen it, I think the unit is "choice list" or similar. I suppose we could convert the % to a unit. For now, the function I am working on notes that it is a percentage in the flag column that comes out with the resultant df.

**Comment by cristinamullin** [comment]
That sounds like a good approach for now. In a future update, if we know for sure it is a percentage I would feel comfortable changing the TADA unit field to %. That way in the shiny app and other functions down the line will have % there instead of "choice list" which is ambiguous/not very useful in this case.

**Comment by ehinman** [comment]
@cristinamullin Sounds good to me! That would be easy to implement.

**Comment by ehinman** [comment]
@cristinamullin Another sticky example entry to discuss: "# - #". I'm noticing in the depth height measure columns, sometimes people put in "0-2" as a depth measurement. Currently, this is "Coerced to NA". I'd be interested to hear (a) how people use these ranges in their analyses and (b) how they would suggest handling it in TADA. My first instinct is to calculate an average so these values are usable, e.g. "0-2" becomes 1. But I may be misinterpreting the entry. For example, maybe result value is representative of all depths between 0 and 2, as opposed to representative of a depth somewhere between 0 and 2.

**Comment by cristinamullin** [comment]
Great catch!

Yes and Yes: it is safe to assume in this case the value is BOTH "representative of all depths between 0 and 2" and "representative of a depth somewhere between 0 and 2". 

The upper 2m is typically referred to as the "surface" layer, and I think it is safe to assume measure values with 0-2m here are representative of the "surface". However if we want to plot this on a depth profile, we could use the avg like you suggest, or assume the value is the same from x = 0 to 2m down (either option works depending on if we are drawing a line vs scatter plot). 

However for making this field numeric, let's go with the avg (1m in this example) as the NUMERIC value for the depth field. There is also a metadata element where users can specify that this is a "surface" result, and we could/should probably make sure that is filled out here too in this step.

Let me know if you find others (not just 0-2), as we likely need slightly different logic for each scenario

**Comment by cristinamullin** [comment]
@ehinman  I think most of this is complete now. Can you please review & create new issues on specific topics here if there is anything outstanding? Thank you!

**Comment by ehinman** [comment]
Sounds good!
