### ISSUE TITLE
Mapping error

### ISSUE THREAD

**Issue by anbethe** [USEPA/TADA#192]
I am using the WQPDataHarmonization Rmd vignette, pulling data for Alaska. When running the checks for Invalid Coordinates, I get a couple of errors and am unable to create a map of Alaska sites. 

Here is the code for pulling data
TADAProfile <- TADAdataRetrieval(statecode = "AK", characteristicName = c("Fecal Coliform", "Escherichia coli", "Enterococcus"), startDate = "05-01-2018")

I get an error in the below portion of the coordinates checking, this is the only portion of this code section with an obvious choice for specifying a specific state. The prior map options (USA map, state outlines, county outlines) only show the continental US , and none of them map my Alaska sites. It's possible that there are no mapped counties for Alaska. Alaska has boroughs, these are typically used to replace counties in maps, but I'm not sure if that's the case with the source utilized here.

maps::map('county', 'alaska')

Error in map.poly(database, regions, exact, xlim_tmp, ylim, boundary,  : 
  no recognized region names

**Comment by cristinamullin** [comment]
@anbethe thanks for catching this bug as well! Unfortunately, it seems like the _maps_ package doesn't work for AK. I am working on some updates that will use a different R package for mapping that will be able to map AK, HI, and other territories that are missing. Updates coming shortly!

**Comment by ehinman** [comment]
This issue should be fixed with the latest pull request to develop - "add_map_vignette_eh"
