### ISSUE TITLE
Update AggregatedContinuousData Function - PSEUDO-DEVELOP ATTEMPT

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#204]
This flag is useful, but does not currently catch all aggregated data. It should be updated to look at other fields as well to flag aggregated data. 
https://usepa.github.io/TADA/reference/AggregatedContinuousData.html

e.g. Field observation, Activity, Stats attached, qualifier codes

**Comment by ehinman** [comment]
I made some edits to the AggregatedContinuousData flag function. These are the filters used, based on the continuous data template:

cont.data = .data%>%dplyr::filter((ActivityTypeCode=="Field Msr/Obs"&ResultDetectionConditionText=="Reported in Raw Data (attached)")|(ActivityTypeCode=="Field Msr/Obs"&SampleCollectionEquipmentName=="Probe/Sensor"&!is.na(ResultTimeBasis)&!is.na(StatisticalBaseCode)&ResultValueTypeName=="Calculated"))

- ActivityTypeCode = Field Msr/Obs + Result Detection Text indicates attachment
OR
- ActivityTypeCode = Field Msr/Obs 
- Sample collection equipment = Probe/Sensor
- Result Time Basis is not NA
- Statistical Base Code is not NA
- ResultValueTypeName is Calculated

**Comment by ehinman** [comment]
Can we close this? Is this line sufficient for catching continuous data?

 cont.data = .data%>%dplyr::filter((ActivityTypeCode=="Field Msr/Obs"&ResultDetectionConditionText=="Reported in Raw Data (attached)")|(ActivityTypeCode=="Field Msr/Obs"&SampleCollectionEquipmentName=="Probe/Sensor"&!is.na(ResultTimeBasisText)&!is.na(StatisticalBaseCode)&ResultValueTypeName=="Calculated"))
