### ISSUE TITLE
autoclean function - filter activity media to WATER?

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#211]
The TADA function autoclean has the following code lines:
  
`
.data <- dplyr::filter(.data, ActivityMediaName == "WATER")
`
I was trying to come up with a test for this function -- like checking that there are no dropped ResultIdentifiers -- but then realized that this function removes records and doesn't track their removal. I might suggest we comment out this line for now? I think it makes more sense to either specify WATER at the outset of the data query, or flag and remove non-WATER media elsewhere in the package/flow.

@cristinamullin Thoughts?

**Comment by cristinamullin** [comment]
I agree, let's remove autoclean from the data retrieval functions and making it a stand alone function. That way we can capture rows that are removed in the R Shiny app/data frame where records that are flagged will go. We should start to incorporate that workflow into the vignette as well (to make sure the functionality works as desired). In this scenario, autoclean should work like the rest of the flag functions. Where it can return a clean dataframe, flag dataframe, or removed records only dataframe. 

I am also okay with potentially breaking up autoclean into smaller more specific functions (e.g. we could make the media filter it's own function, but filtering can already be accomplished with the filter functions).
