### ISSUE TITLE
Find Nearby Stations - latitude/longitude precision flag

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#218]
**Is your feature request related to a problem? Please describe.**
Monitoring locations have varying levels of location precision recorded in WQP. Generally, low precision occurs when there are 3 or fewer digits after the decimal (>500 m precision threshold). However, it can be hard to discern whether the 3 or fewer digits after the decimal are real or a product of truncation by programs such as Microsoft Excel, where a decimal degree value of 49.01000000 is a real location, but Excel might convert it to 49.01. This truncated value is then translated into the data uploaded to WQX. It might be inappropriate to assume low precision, but true low precision can cause issues in data location accuracy--we cannot always know what bin these measures fall into.

**Describe the solution you'd like**
One important facet of TADA is to aggregate data for analysis. Often, multiple agencies will collect data at the same monitoring location, but use their own metadata to describe the location. In this case, it might make sense to combine multiple sites into one representative site, where data may be combined or compared. However, sites sometimes appear to have different levels of location precision, making it difficult to ascertain whether the data are representative of the recorded location. One solution is to flag sites with low location precision, where low precision occurs when there are three or fewer digits after the decimal in the decimal degree value. This could be a check included in the Find Nearby Stations function to be developed for TADA. It may not necessarily be a grounds for site rejection, but might be something users would want to know about and factor into their analyses.

**Describe alternatives you've considered**

**Additional context**

**Comment by cristinamullin** [comment]
Elise comment: 
Regarding InvalidCoordinates: What is the basis for removing lat/longs with fewer than 3 decimal digits? A test dataset I ran through it flagged a lot of USGS sites that didn't necessarily seem erroneous, but perhaps did land in the vicinity of ##.##000? How do we know less than 3 digits is imprecise vs ending in 0000...?

**Comment by cristinamullin** [comment]
Related note: R natural earth package within maps package, uses spatial datasets, may be helpful for finding lat/longs that do not match the provided state, county, etc. (from Katie's research)

**Comment by cristinamullin** [comment]
Most of this issue has already been addressed or is now included here: https://github.com/USEPA/TADA/issues/474
