### ISSUE TITLE
PotentialDuplicate_RowID

### ISSUE THREAD

**Issue by jakegreif** [USEPA/TADA#22]
### Page Requirements/Standards
All of the flag page functions should be consistent in the following ways:
- Clean argument indicates whether flag columns should be appended to the data (clean = FALSE), or flagged data is transformed/filtered from the dataset and no columns are appended (clean = TRUE).
- Default is clean = FALSE

### Function Requirements
- Reference table required?
No
- Include warning if flags are not applied?
No
- Required columns:
ActivityIdentifier
ActivityConductingOrganizationText
OrganizationFormalName
OrganizationIdentifier
ProjectIdentifier
ResultCommentText
ActivityCommentText

### Development Notes
- ResultFlagsIndependent.R
- Required columns are those that are not included when checking for duplicates
- Use code from "auto clean" function
- Flag is unique identifier for each unique row (identical IDs = duplicate row)

**Comment by ehinman** [comment]
How pervasive is this duplicated data submission issue? I have an example from Utah (see attached), but it's so mired down by the unique submission styles of each organization that one would not know they were necessarily duplicates without knowing the org-specific sites are right on top of one another. It might instead make more sense to flag for review records with the same date, time (?), result value within rounding error (yep, we noticed differences in rounding conventions between two orgs submitting the same data), similar lat/longs from different organizations. At the very least, it's important to note that ResultIdentifier needs to be an excluded column....each record has its own unique ResultIdentifier, regardless of they are organization duplicates. 
[slcows_dwq_dupdat.csv](https://github.com/USEPA/TADA/files/10710664/slcows_dwq_dupdat.csv)

**Comment by cristinamullin** [comment]
I agree it will be difficult to find the more nuanced examples like the one you've shared. This main function of this potential duplicates function, is to catch duplicates that are submitted to the WQP twice, by two different organizations. This is fairly common, and can occur when both the state and other organizations submit the exact same datasets, but the organization ID and metadata is the only thing different. I have also seen a lot of exact duplicates (but that is covered as part of autoclean currently - I know we need to discuss that as well though, since it is slow.

**Comment by ehinman** [comment]
Is there a good example that I can review? I need to wrap my mind around it a little more. I would think that the differences in metadata might vary organization to organization, such that it might be hard to rely on a majority of columns containing the exact same information between organizations (ex. can we be sure one organization doesn't use a comment text field differently from another?). I tried running it using the example data, Nutrients_Utah, but it didn't seem to find any duplicates given the columns unique'd.

Re: exact duplicates, I'm interested to hear your thoughts on the updates I made to autoclean, which in the pull request relies only on ResultIdentifier to identify (potential) exact duplicates. It speeds the process up quite a bit.

**Comment by ehinman** [comment]
I have been working on a function that identifies potential duplicates based on characteristic name, activitystartdate, activitystarttime.time, and whether those are within 10% of each other submitted by two organizations. I also created an idNearbySites function that then looks for sites within some buffer distance of each other. This function is incorporated in the identify duplicates function as another check. Accordingly, the function flags records with nearly identical metadata at sites within the specified distance buffer. I've been testing it and it appears to be a pretty sufficient first pass. The issue I need input on is how we want to display this information and how we want users to be able to navigate these duplicates.
