### ISSUE TITLE
Special characters in MeasureValue fields that involve # - # - PSEUDO-DEVELOP FIX

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#225]
**Is your feature request related to a problem? Please describe.**
EDH: Sometimes people put in "0-2" as a depth measurement. Currently, this is "Coerced to NA". I'd be interested to hear (a) how people use these ranges in their analyses and (b) how they would suggest handling it in TADA. My first instinct is to calculate an average so these values are usable, e.g. "0-2" becomes 1. But I may be misinterpreting the entry. For example, maybe result value is representative of all depths between 0 and 2, as opposed to representative of a depth somewhere between 0 and 2.

**Describe the solution you'd like**
CM: For making this field numeric, let's go with the avg (1m in this example) as the NUMERIC value for the depth field. There is also a metadata element where users can specify that this is a "surface" result, and we could/should probably make sure that is filled out here too in this step.

**Describe alternatives you've considered**
CM: The upper 2m is typically referred to as the "surface" layer, and I think it is safe to assume measure values with 0-2m here are representative of the "surface". However if we want to plot this on a depth profile, we could use the avg like you suggest, or assume the value is the same from x = 0 to 2m down (either option works depending on if we are drawing a line vs scatter plot).

**Additional context**

**Comment by cristinamullin** [comment]
Somewhat related to this issue on depth profile data: https://github.com/USEPA/TADA/issues/149
