### ISSUE TITLE
Special characters function handling of percentages (%)

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#226]
**Is your feature request related to a problem? Please describe.**
ConvertSpecialChars function will remove the character "%" from a result value so it can be used as a numeric value, but it doesn't change the result unit to "%". This change is, however, tracked in the TADA.ResultValueDataTypes.Flag column, where the entry is "Percentage". 

**Describe the solution you'd like**
Convert TADA.Unit to "%".

**Describe alternatives you've considered**
But, need to check if over-writing the pre-existing unit could be problematic. Currently, EDH has mostly seen the unit in these situations as "Choice List", which isn't any more informative than "%".

**Additional context**

**Comment by jbousquin** [comment]
I've overwritten as fraction (0/100), so that it can be treated like ppm etc. Only concern would be if that makes it prone to being entered inconsistently (e.g., 50% vs 0.5).

**Comment by hillarymarler** [comment]
I think this may have been addressed with the previous updates to TADA_ConvertSpecialChars. I will look at some test data sets with "Choice List" units for percentage data to verify.

**Comment by hillarymarler** [comment]
Some of the choice list options include the ">" or "<" in a percentage range. For example, ">0-25%". I am working on updating the code so that this will be flagged as "Percentage Range - Averaged" and included in the averaging calculations (if user specifies that percentage averages should be calculated).

**Comment by hillarymarler** [comment]
@cristinamullin - if a result is both a percentage and a greater or less than such as "<1%" should that show up labeled as "Percentage" or "Less Than"?

**Comment by cristinamullin** [comment]
I think "Less Than" is better in this case since the % can be captured as the unit
