### ISSUE TITLE
censored data functions choke when there are no censored data records

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#245]
**Describe the bug**
Censored data summary function will break if there isn't any censored data in the dataset.

**To Reproduce**
1. download all PUEBLO_POJOAQUE data using TADAdataRetrieval
2. run summarizeCensoredData
3. See error message about replacement rows.

**Expected behavior**
The app should return the input dataset with a message "No censored data to summarize, returning input dataset"

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cristinamullin** [comment]
Note that errors show up for both summarizeCensoredData and simpleCensoredMethods even when only numeric data is in the df. They are just not happy there is no censored data.
