### ISSUE TITLE
Get...Ref functions - export from TADA?

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#273]
**Is your feature request related to a problem? Please describe.**
When working on the training materials, I thought it might be helpful to allow users to see the reference tables. 

**Describe the solution you'd like**
I'd like to export the Get...Ref functions from TADA

**Describe alternatives you've considered**
The current alternative is that users must go to the WQX domain page to find these reference tables, and some of the ones within the package have additional columns added by TADA.

**Additional context**

**Comment by cristinamullin** [comment]
Good idea! Yes, let's export these
