### ISSUE TITLE
Harmonization template duplicated for certain characteristics

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#275]
**Describe the bug**
When running TADA::Nutrients_Utah through the vignette, I noticed that the dataframe grew in number of records after TADA::HarmonizeData. I realized that this is because there are multiple reference values in the harmonization table for one characteristic-fraction-speciation-unit combination. This is true of the comparable data identifier: Total Nitrogen, Mixed Forms_as N_mg/L

**To Reproduce**
1. Run vignette with TADA::Nutrients_Utah
2. Run TADA::HarmonizeData 
3. Run table(TADAProfileClean6$ResultIdentifier)[table(TADAProfileClean6$ResultIdentifier)>1], see duplicated records due to many to many join in table.

**Expected behavior**
Table should be a one to many join. Result dataset should not grow in size. We might want to add a check for this in any functions that perform merges.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ehinman** [comment]
Another thing I noticed: many of these rows have the TADA.ResultMeasure.MeasureUnitCode = MG/L, which is not currently the target unit (UG/L). Will correcting these cause issues (besides needing to update the conversion factor to get to MG/L)?

**Comment by cristinamullin** [comment]
Good catch. Assuming that unit conversions happen before this function would be run, then for these rows TADA.ResultMeasure.MeasureUnitCode should equal "UG/L". We could convert again to a characteristic specific unit using TADA.SuggestedResultUnit (for priority chars), but I am not sure if that should be included in this table/function. Alternatively we could save the characteristic specific unit conversions for the next module ?
