### ISSUE TITLE
Identifying censored data

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#323]
**Is your feature request related to a problem? Please describe.**

The censored data functions do not consider the user supplied MeasureQualiferCode when identifying censored data for handling and generating statistics. 

**Describe the solution you'd like**

Add logic to the censored data functions to look at the new TADA.MeasureQualifierCode.Flag field for results categorized as "Non-Detect" or "Over-Detect" based on the user supplied MeasureQualiferCode. We may need to run TADA_FlagMeasureQualifierCode in autoclean (or within the censored data functions if the column TADA.MeasureQualifierCode.Flag does not already exist) to facilitate this. 

**Reminders for TADA contributors addressing this issue**

New features should include all of the following work:

-   [ ] Create the function/code.

-   [ ] Document all code using comments to describe what is does.

-   [ ] Create tests in tests folder.

-   [ ] Create help file using roxygen2 above code.

-   [ ] Create working examples in help file (via roxygen2).

-   [ ] Add to appropriate vignette (or create new one).

**Comment by hillarymarler** [comment]
I'd like to work on this one. It may solve a few problems I'm encountering while working on the pathogen censored methods.

**Comment by cristinamullin** [comment]
Great! I think this additional logic for id'ing censored data based on the MeasureQualiferCode and the TADA.MeasureQualifierCode.Flag column added by this function (https://usepa.github.io/TADA/reference/TADA_FlagMeasureQualifierCode.html) could be included in the TADA_IDCensoredData function: https://usepa.github.io/TADA/reference/TADA_IDCensoredData.html

TADA_IDCensoredData runs within autoclean (https://usepa.github.io/TADA/reference/TADA_AutoClean.html) and/or in the simple censored data handling function (https://usepa.github.io/TADA/reference/TADA_SimpleCensoredMethods.html).

**Comment by hillarymarler** [comment]
After running TADA_FlagMeasureQualiferCode, I used TADA.MeasureQualifierCode to identify additional censored results by filtering for "Non-Detect" and "Over_Detect". These results are then grouped with the other censored data and proceed through the rest of the function together.

Is that similar to what you had in mind? I am trying to think of any places farther along in the workflow that would need modification to include the newly identified censored results correctly, but haven't thought of any yet. I'll keep running some test data sets and see if any I spot any issues.
