### ISSUE TITLE
Scatterplots require ALL TADA depth columns for plotly hovers, but they may not be present if WQP column is entirely NA

### ISSUE THREAD

**Issue by ehinman** [USEPA/TADA#332]
**Describe the bug**

Currently, the TADA.....DepthHeight columns are created in autoclean via the TADA_ConvertDepthUnits() function. This function ONLY creates a TADA.....DepthHeight column IF there exists at least one value in the column that is not NA. Therefore, if the entire depth column is NA, the TADA.... depth column is not appended to the dataframe. This is problematic for the scatterplot functions, which have hover text that displays ALL TADA.... depth column info. It may throw an error if the column is missing from the dataset...but should it? I almost made all the TADA.... depth columns required to run the function, but then I wasn't sure if that was the right approach, since it conflicts with the logic of the convert depth units function. Suggest unification of approaches.

**Additional context**

Solutions could be:
- create hover text object outside of the plotly plot and make it flexible to the available depth columns
- add TADA.... depth columns to every dataset regardless of whether entire WQP column is NA
- add empty TADA.... depth columns to plotting dataset just prior to drawing plot

**Reminders for TADA contributors addressing this issue**

New features should include all of the following work:

-   [ ] Create the function/code.

-   [ ] Document all code using comments to describe what is does.

-   [ ] Create tests in tests folder.

-   [ ] Create help file using roxygen2 above code.

-   [ ] Create working examples in help file (via roxygen2).

-   [ ] Add to appropriate vignette (or create new one).

**Comment by cristinamullin** [comment]
Decided to add TADA.... depth columns to every dataset regardless of whether entire WQP column is NA. This deals with unit synonym issues like "meters" and "m" even if it does not convert the units. Creating new issue regarding carrying through extra columns that are no longer needed (original vs TADA columns).
