### ISSUE TITLE
Original vs. TADA columns (copies)

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#336]
**Is your feature request related to a problem? Please describe.**

Currently, autoclean adds copies of TADA depth columns even if all values within the original column are NA. This means we now have two copies of the same data with all NA's. However, some downstream functions require these columns to run, even if they are all NA (e.g. scatterplots & other analysis to come). 

Not sure of a good solution, or even if this is a major issue. It may only be an issue within the R Shiny web app. My concern is with regards to carrying data through the process that is not needed (and memory issues in the R Shiny app). The issue goes beyond this one example, to the fact that we have original and TADA versions of many columns. This is done for transparency, but makes the dataframe much larger than it would be if we only had one version (the clean version), and did not always carry the originals through.

**Comment by hillarymarler** [comment]
What about a function that would select only the TADA versions of the columns? It could be run after the user reviews flags, differences between TADA and original versions, etc. so the non-TADA columns would be not be carried through to scatterplots and other analysis. For the R Shiny app, maybe it could be presented as a button or toggle on/off indicating the user has accepted all TADA values for further analysis within the app.

**Comment by cristinamullin** [comment]
I like this idea. This could be one of the last steps in the Shiny app and/or the first step in the next Shiny app. As a stand alone package function, a user could run it at any time. This same function could possibly also remove non-essential and completely empty columns...  as long as removing them would not cause issues with other TADA functions with specific required columns.

**Comment by hillarymarler** [comment]
Is there a list of essential columns for functions in the Shiny app? I'd like to work on this.

**Comment by cristinamullin** [comment]
See TADA_CheckRequiredFields() in Utilities.R. Currently this function is draft and not included in the Mod 1 vignette or the shiny app. It is not exported either so package users don't have access yet. 

In this function, I started to work on the list and categorized them by those that are required (used directly in TADA functions), not needed/used at all, and not used in TADA functions but should still be carried through for data interpretation. It is not comprehensive yet and we still need to double check that all are categorized correctly.

**Comment by cristinamullin** [comment]
I noticed that we have two original columns that are duplicates but one is misspelled: "MethodSpeciationName" and "MethodSpecificationName". And then we also have TADA versions of each of these: "TADA.MethodSpecificationName" and "TADA.MethodSpeciationName". 

Can you please address this as part of this issue? I think we should use "MethodSpeciationName" (original) and "TADA.MethodSpeciationName" (TADA only).

**Comment by hillarymarler** [comment]
Yes - I can address as part of this issue. Good catch!

**Comment by hillarymarler** [comment]
I ran into an unexpected issue when addressing the MethodSpecification vs. MethodSpeciation part of this. Only MethodSpecification NOT MethodSpeciation are available through the Narrow and Sampling Activity Metrics profiles. 

So I could change the TADA column name, but it would still be based on MethodSpecification. Should I do that? Or will upcoming changes to WQX profiles address  MethodSpecification vs. MethodSpeciation?

**Comment by cristinamullin** [comment]
The new profiles will address this spelling issue, so we can use MethodSpecification for now since that is what is in the WQP services/profiles now. I am not sure where MethodSpeciation was introduced (via a TADA function or USGS's dataRetreival?).
