### ISSUE TITLE
USGS only detection limit units

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#338]
USGS only units copied from detection limit unit columns still contain speciation. Update TADA_ConvertResultUnits which is run within autoclean to deal with speciation in detection limit units as well. See example output below for the nutrients UT example data file.

[TADAShiny_datadownload_Harmonize.xlsx](https://github.com/USEPA/TADA/files/12541158/TADAShiny_datadownload_Harmonize.xlsx)

**Comment by cristinamullin** [comment]
Currently, the only place we address this issue with USGS data having speciation in the result value is in TADA_ConvertResultUnits using the USGS_units_speciation.csv. If a user doesn't first run autoclean before running TADA_ConvertResultUnits, then the detection limit values and units are not copied to result units and values (this only happens now within autoclean). I think this is why these other issues with the USGS only units and speciations are also not addressed. 

One solution may be to update the TADA_ConvertResultUnits so it works more like TADA_ConvertSpecialChars in that there can be a function input to specify the field to run the function on (the user could specify to run it on the result value and unit fields or detection limit value and unit fields). For example: 
  test1<- TADA_ConvertSpecialChars(.data, "ResultMeasureValue")
  test2<- TADA_ConvertSpecialChars(.data, "DetectionQuantitationLimitMeasure.MeasureValue")

**Comment by hillarymarler** [comment]
I believe this issue was solved as part of: Detection limit unit conversions #378
(https://github.com/USEPA/TADA/issues/378)
