### ISSUE TITLE
Dealing with pathogen nondetects

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#356]
**Is your feature request related to a problem? Please describe.**

TADA's simple censored data function does not allow for characteristic specific non-detect handling, e.g., bacteria. Regardless of the method chosen and applied for all other characteristics, should bacteria (e.g. e. coli) always default to a whole number close to zero such as 1-2  Colony Forming Units (CFU) or Most Probable Number (MPN) per 100 mL? Does applying a single method across all characteristics cause issues for any other characteristics/characteristic groups in addition to bacteria?

Here are the notes from the meeting in Jan 2021 where we discussed nondetect handling methods: 
  Subgroup A
 [ IssuePaper_RetrievalQAQC_Jan2021.docx](https://usepa.sharepoint.com/:w:/r/sites/AutomatedDataAnalysisWorkingGroup/_layouts/15/Doc.aspx?sourcedoc=%7BC74D9A1C-DCEE-46B1-AC07-E05AD63E2714%7D&file=IssuePaper_RetrievalQAQC_Jan2021.docx&action=default&mobileredirect=true)

There is some more information in the TADA Master List of Requirements (starting on pg 12). 
“Substituted values can include the reporting limit or a very low pathogen count (1 to 2 Colony Forming Units (CFU) or Most Probable Number (MPN) per 100 mL). A concentration of 0 CFU or MPN per 100 mL is not typically used because the summary statistic used for pathogens (geometric mean) cannot be calculated when the dataset includes zeros.”
 [ TADA Master List of Requirements.docx](https://usepa.sharepoint.com/:w:/r/sites/AutomatedDataAnalysisWorkingGroup/_layouts/15/Doc.aspx?sourcedoc=%7B62DB0D15-F4EC-4753-9358-1D2B288F436B%7D&file=TADA%20Master%20List%20of%20Requirements.docx&action=default&mobileredirect=true)

**Comment by hillarymarler** [comment]
<img width="346" alt="image" src="https://github.com/USEPA/TADA/assets/152432687/8e1a18bc-ca50-41e1-a003-ceb891c04d91">

Working on this using Fecal Coliform as an example. I noticed that "MPN/100ML" and "MPN/100 ML" are both listed in TADA.ResultMeasure.MeasureUnitCode. It does not impact adding a simple censor option for pathogens, but maybe something to keep in mind.

**Comment by cristinamullin** [comment]
Excellent! Let me know if you run into any questions or issues with the "MPN/100 ML"  to "MPN/100ML" unit synonym conversion. 

Regarding the issue with Maryland data with the result value  "." being coerced to NA... I looked at the data and don't see any metadata included that we could use to identify that data as censored, or that indicated how the result value "." should be interpreted. Currently, all non-numeric results like this that cannot be easily interpreted or wrangled end up getting removed. 

My initial thought is that the censored data functions should only handle the data we are able to ID as censored data based on the metadata provided in the Detection Limit Type Name, Result Detection Condition Text, and possibly the MeasureQualifierCode (other issue your working on). I don't think the censored data function should act on non-censored data. 

Would make more sense to include substitutions for negative values within a new geometric mean calculator function?

**Comment by hillarymarler** [comment]
I like the idea of a geometric mean calculator function. That would be an appropriate place to substitute negative or zero values.

Do you think TADA.SimpleCensoredMethods should handle substitutions for non-detect pathogen data with additional substitutions for non-censored data in the geometric mean function? Or should all substitutions happen in the geometric mean function?

**Comment by cristinamullin** [comment]
Yes I think TADA.SimpleCensoredMethods should handle substitutions for non-detect pathogen data, with additional substitutions for non-censored data in the geometric mean function. 

I think most states do calculate a geometric mean for bacteria, but many do not (https://usepa.sharepoint.com/:x:/r/sites/WQPDataAssessmentTeam/_layouts/15/Doc.aspx?sourcedoc=%7B49ACC717-A45E-41F0-9F3F-00BAE8743D81%7D&file=Summary%20of%20CALMs.xlsx&action=default&mobileredirect=true). 

I recommend the separating these two because the censored data substitutions should be included as a pre-requisite for any assessment methodology (any criteria/methodology), but the substitutions for negative values may only be needed if the assessment method includes calculation of the geomean. Some E. coli, enterococci, and fecal coliform assessment criteria and methods simply use a "not to exceed x percent of the time" methodology (e.g. AZ: fecal coliform not to exceed 400 cfu/100mL more than 25% of the time from may-sept with a min of 8 samples evenly distributed across the season). In that case, the TADA user would still need to run the censored data substitutions function, but wouldn't need the neg value substitutions from the geometric mean function.
