### ISSUE TITLE
Range percent values (26-50%) not handled correctly in TADA_ConvertSpecialChars

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#375]
Query 
startDate
"2014-05-23"
endDate 
"2014-05-24" 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/cmulli01/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/cmulli01/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</head>

<body link="#0563C1" vlink="#954F72">

ResultMeasureValue | TADA.ResultMeasureValue | ResultMeasure.MeasureUnitCode | TADA.WQXResultUnitConversion | TADA.ResultMeasureValueDataTypes.Flag
-- | -- | -- | -- | --
0% | 0 | % | No Conversion Needed | Percentage
0% | 0 | % | No Conversion Needed | Percentage
26-50% | NA | % | No Conversion Needed | Percentage
26-50% | NA | % | No Conversion Needed | Percentage
0% | 0 | % | No Conversion Needed | Percentage
0% | 0 | % | No Conversion Needed | Percentage
1-5% | NA | % | No Conversion Needed | Percentage
1-5% | NA | % | No Conversion Needed | Percentage
1-5% | NA | % | No Conversion Needed | Percentage

</body>

</html>

**Comment by hillarymarler** [comment]
What is the desired value for TADA.ResultMeasureValue? An average for the range?

**Comment by cristinamullin** [comment]
As is, it is the TADA.ResultMeasureValueDataTypes.Flag that is incorrect. We could change that flag for these to "Text" so they would be flagged for removal based on that. Or we could calculate the average and include that as the TADA.ResultMeasureValue. Personally, I prefer that option (using the average), but we could double check with the working group.

**Comment by cristinamullin** [comment]
@hillarymarler Within TADA_ConvertSpecialChars, can we add the unit as % to TADA.ResultMeasure.MeasureUnitCode as well for these even though the original unit is NA?

![image](https://github.com/USEPA/TADA/assets/46969696/e7f44d33-63ab-40d9-8ff7-03aeb4e02d86)


``` r
test = TADA_DataRetrieval(startDate = "2014-05-23", endDate = "2014-05-24")
subset = test %>% select(c("ResultMeasureValue", "TADA.ResultMeasureValue", "ResultMeasure.MeasureUnitCode", "TADA.ResultMeasure.MeasureUnitCode", "TADA.WQXResultUnitConversion", "TADA.ResultMeasureValueDataTypes.Flag"))
```

**Comment by hillarymarler** [comment]
I made this change and updated the pull request.

**Comment by cristinamullin** [comment]
I found one scenario in the example dataset that was still not translating correctly. Adding a commit to your PR to fix

![image](https://github.com/USEPA/TADA/assets/46969696/d6c14315-b4a8-4ac8-8cc1-adb2597032ba)
