### ISSUE TITLE
CensoredData

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#40]
Function title: CensoredDataSubstitutions or TransformCensorData?

**Generate DetectionQuantitationLimitTypeName (and associated DetectionQuantitationLimitMeasure/MeasureValue and DetectionQuantitationLimitMeasure/MeasureUnitCode) and ResultDetectionConditionText from Result Value where needed**

Depends on ResultsSpecialChars Function:
- Convert Result Values that start with "<" into an appropriate Detection Condition and Detection Limit Value. That is: a Result Value of "<0.25" would be converted into a ResultDetectionConditionText of "Present Below Quantification Limit", a Nondetect Result Value of "0.25", and a DetectionQuantitationLimitTypeName of "Lower Quantitation Limit"

Two options (best for when <70% of data are censored): 
- Robust ROS [Regression on Order Statistics (ROS)] (for lower limits, use random number between detection limit and 0)
- x times the detection limit

**Comment by cristinamullin** [comment]
Notes about detection limit from Christy Meredith Montana DEQ

"If the ResultMeasureValue=NA, usually that means that the measurement is below the detection limit, not that there wasn’t a measurement. So I usually replace it with the detection limit or half the detection limit (Montana DEQ protocol). I’m not sure what other people do, but this functionality could be added".

**Comment by cristinamullin** [comment]
FROM: 
'**Dennis Helsel**' <dhelsel@practicalstats.com>
pauljulianphd@gmail.com
Lee, R. Lopaka <rclee@usgs.gov>

Glad you got in touch!  Yes, officially I'm retired as of this past April.  But I've kept my hand in the nondetects / WQ world a little bit, however.  I've been advising an international group of SETAC scientists on data analysis for censored data.  You'll see two results of that on the Videos section of practicalstats.com, a webinar presentation to Australian scientists titled "Two Things I've Learned After 43 Years of Applying Statistics to Environmental Science", and a webinar to the entire SETAC group on why better methods for censored data need to be used in WQ titled "The Cost of Complacency".  Both were given and recorded this past spring. Both might be of interest to your workgroup.

I've also continued to add a bit to the NADA2 package.  Paul has just posted a new version of NADA2 that includes a new function I wrote for trend analysis after adjusting for a covariate, a non-time variable like streamflow or depth to water. I hope to write a few more new functions in the coming year(s), at my own pace of course. The new version of
NADA2 includes a tutorial Paul and I wrote on stats for censored data, listed as a "vignette" -- that's the best place to start for your working group to learn about how NADA2 can be leveraged for their workflows.  It can be downloaded from the NADA2 page on the CRAN site and uses examples from the Nondetects And Data Analysis course I taught for over a decade, and which is now available online at practicalstats.com for free.  Perhaps someone in the working group might benefit from taking that course and reporting back to the others?  Or perhaps someone in the group already has taken it.

As far as a presentation, if you want someone to discuss the stats of the methods in NADA and NADA2, I'm probably your guy.  I'd do an online presentation; probably not one in person unless the location is somewhere I really want to go to (Charleston, SC, say). If instead you want someone to speak about programming and interfacing with the packages, Lopaka or Paul would be the ones to ask.

One of the nice things about retirement is that I avoid conference calls.  If the objectives of a call are laid out explicitly and a time limit for it set, a call might be OK.  For the topics of stats, what the packages do and why they're important, I'd prefer your workgroup instead put together questions and send them to me, and I'll answer them by email rather than a video call.  I find that more efficient. If the topic is the computer aspect of the TADA effort Lopaka and / or Paul will have to speak for their own time and interest.

Best regards, and best wishes on the work, Dennis Helsel

**Comment by cristinamullin** [comment]
@ehinman can this be closed?

**Comment by ehinman** [comment]
Mostly, yes. The basics are there to ID non-detects and use simple methods to fill them (x times detection limit, random number between detection limit and 0). However, we do not currently handle more complex approaches to handling nondetects that depend upon the detects in the dataset (Robust ROS, MLE, Kaplan-Meier), just offer suggestions in the summary. Should I create a new issue for this?

**Comment by cristinamullin** [comment]
@ehinman awesome!!! let's use this [issue](https://github.com/USEPA/TADA/issues/53) for that & close this one
