### ISSUE TITLE
TADA_AnalysisDataFilter bug

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#402]
**Describe the bug**

TADA_AnalysisDataFilter should not remove any results if clean = FALSE.

Note: this function runs slowly. Is it possible to speed it up?

**To Reproduce**

``` r
# Currently returns data frame with ONLY surface water results (removes groundwater and sediment data) and adds TADA.UseForAnalysis.Flag column
Data_6Tribes_Assessment2 <- TADA_AnalysisDataFilter(Data_6Tribes_5y_Harmonized, clean = FALSE, surface_water = TRUE, ground_water = FALSE, sediment = FALSE)
```

**Expected behavior**

When clean = FALSE, the function should return all data with TADA.UseForAnalysis.Flag column populated according to the specifications in the other function inputs. For example, 

Data_6Tribes_Assessment2 <- TADA_AnalysisDataFilter(Data_6Tribes_5y_Harmonized, clean = FALSE, surface_water = TRUE, ground_water = FALSE, sediment = FALSE)

should return TADA.UseForAnalysis.Flag with values: "Yes - SURFACE WATER",  "No - GROUND WATER", and "No - SEDIMENT". All rows should have a TADA.UseForAnalysis.Flag.

**Other**
•	Add TADA_AnalysisDataFilter to flag page of shiny app
o	Run TADA_AnalysisDataFilter(Data_6Tribes_5y_Harmonized, clean = FALSE, surface_water = TRUE, ground_water = TRUE, sediment = TRUE)
	Specify what to do with each TADA.UseForAnalysis.Flag column value
•	"Yes - SURFACE WATER"
•	"No - SURFACE WATER"
•	"Yes - GROUNDWATER"
•	"No - GROUNDWATER "
•	"Yes - SEDIMENT"
•	"No - SEDIMENT"
•	“No - OTHER”

**Comment by cristinamullin** [comment]
@hillarymarler can you look into this one?

**Comment by hillarymarler** [comment]
Sure - I can take a look at this.

**Comment by cristinamullin** [comment]
Looks great. The only things I noticed is that the function returns the TADA.Media.Flag. Should that be removed?
