### ISSUE TITLE
Whole numbers for characteristic and measurement legends in TADA_OverviewMap

### ISSUE THREAD

**Issue by hillarymarler** [USEPA/TADA#410]
1) Measurement count legend on “Explore” Tab should be whole numbers5.	
2) The Characteristics legend in the map on the Overview tab should just be a whole number count of 1 or 2…etc. 

To reproduce, look at Utah Nutrients data set in package or Shiny app with TADA_OverviewMap.

To fix, modify TADA_OverviewMap so that bins for Characteristics/Measurements are whole number ranges.

-   [ ] Create the function/code.

-   [ ] Document all code using comments to describe what is does.

-   [ ] Create tests in tests folder.

-   [ ] Create help file using roxygen2 above code.

-   [ ] Create working examples in help file (via roxygen2).

-   [ ] Add to appropriate vignette (or create new one).

**Comment by hillarymarler** [comment]
I think the reason this issue is seen with the Utah example data set is because the number of characteristics and sites is relatively small. So the quantiles are going to be fractions as a result.

I do see whole numbers for both with a larger dataset (for example: Data_6Tribes_5y).

Maybe the solution is to have some logic where Sample_Count defines how many pt_size groups are used? So for the Utah nutrient data set, there would only be two colors needed for Parameter_Count since n = 1 or 2 for all records.

**Comment by cristinamullin** [comment]
Good idea. Or if N params per site is <5 in the dataset, maybe the map should not include N params as a color/legend option at all on the map. We could do some testing with different datasets to determine what that minimum should be.

**Comment by hillarymarler** [comment]
Yes - I think we'll need to figure out the N params at which the pretty function should define the breaks. And everything under that would be done using colorFactor and assigning specific colors to specific values (or ranges). I wasn't thinking about organizations measuring fewer parameters (as you mentioned in your pull request comment), but I think that is a good reason to move forward with figuring out an alternate way to color code data sets with fewer parameters in a meaningful way.

**Comment by hillarymarler** [comment]
I think I've got the characteristics as whole numbers figured out. Now the function checks for the length of unique Parameter_Counts in the data set and whether the diff() between values (arranged from smallest to largest) in the Parameter_Counts vectors is the same.

If there are 9 or fewer unique Parameter_Count values AND the interval between them is the same, each whole number is a separate factor for the color palette. If either (or both) of those conditions is not true, then pretty() is used to create whole number bins.
