### ISSUE TITLE
Overview map bug

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#417]
**Describe the bug**

Overview map will not generate for some datasets
https://github.com/USEPA/TADAShiny/issues/139

test = TADA_DataRetrieval(organization = "PECHANGA_WQX")
TADA_OverviewMap(test)
**Error in cut.default(x, binsToUse, labels = FALSE, include.lowest = TRUE,  : 
  'breaks' are not unique**

**To Reproduce**
Code to reproduce the behavior:

``` r
test = TADA_DataRetrieval(organization = "PECHANGA_WQX")
TADA_OverviewMap(test)
# This issue is widespread. e.g. same issue if you query PENOBSCOTINDIANNATIONDNR org 
```

**Expected behavior**
The map should generate.

**Comment by hillarymarler** [comment]
The error is because the parameter counts are all the same. And trying to set the color palette on a single color doesn't work. I've been trying some different options for conditionally setting a single color vs. a palette.

**Comment by hillarymarler** [comment]
I can get circle markers on the map when all of the parameter counts are the same now, but only without the tribal polygons and points. For some reason, I can't get both at once. Trying to figure that out now.
