### ISSUE TITLE
Can't transform a data frame with duplicate names

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#440]
@hillarymarler do you have time to look at this bug? https://github.com/USEPA/TADA/actions/runs/8570448086/job/23488385903?pr=435

It's related to the same issue you were troubleshooting last week:

"Can't transform a data frame with duplicate names."

FYI I also updated the vignettes in the last commit here. Those seems to be working now with no errors. For now, I did have to remove the "answers" in the original R5 vignette. Take a look - you may be able to bring those back in but I wasn't sure how/why they were causing errors.

**Comment by hillarymarler** [comment]
In the example that failed on pr 435, the random data set returned zero results from the WQP. Do you think that could be part of the issue? 

Example TADA_DataRetrieval query was:    
startDate      endDate    statecode 
"2005-01-08" "2005-01-13"         "MI" 

Do you think in general we should update the tests to query for another data set from the WQP if the initial random query yields zero results?

**Comment by hillarymarler** [comment]
Maybe we should just update the random data set functions themselves to re-run until they return a data set with results? I can't think of a situation where returning a test data set with zero results is useful!
