### ISSUE TITLE
TADA_ConvertResultUnits should address common issue with USGS data having speciation in the result AND det limit unit

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#442]
**Describe the bug**

TADA_ConvertResultUnits is not working the same on the result vs det lim fields. 

The code used to update the result value, unit and speciation for specific USGS data is only working on the result value, unit and speciation. This needs updating to work on the det lim columns as well (to pull speciation out of the unit and copy it to the tada speciation). 

This is addresses for the result unit, value, and speciation starting on line 86, more at 162-166 in UnitConversions.R:
usgs.ref <- TADA_GetUSGSSynonymRef()

**Comment by hillarymarler** [comment]
I am looking into this now and can include an update to address this with the other unit conversion changes I've been working on.

**Comment by cristinamullin** [comment]
@hillarymarler that would be great! Thank you
