### ISSUE TITLE
Monitoring location QAQC

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#446]
**Is your feature request related to a problem? Please describe.**

[TADA_FindNearbySites()](https://usepa.github.io/TADA/reference/TADA_FindNearbySites.html)
[TADA_FlagCoordinates()](https://usepa.github.io/TADA/reference/TADA_FlagCoordinates.html)

We have two functions to assist with monitoring location QAQC. One flags nearby sites that may be the same site (same area monitored by multiple orgs or the same org submitted data for the same area multiple times with different monitoring location ID's). The other flags imprecise coordinates and coordinates outside of the US. 

**Describe the solution you'd like**

Users have requested to be able to review the sites on a map before removing them. This may be an R Shiny only feature, but let's explore how we might facilitate this in the R package, potentially using [TADA_OverviewMap()](https://usepa.github.io/TADA/reference/TADA_OverviewMap.html). 

This issue is closely tied with an existing Shiny issue: https://github.com/USEPA/TADAShiny/issues/136
It also ties in with this issue: https://github.com/USEPA/TADA/issues/292

We also have a mock up for this, see:

pages 4-6: https://usepa.sharepoint.com/sites/WQPDataAssessmentTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FWQPDataAssessmentTeam%2FShared%20Documents%2FGeneral%2FTADA%20Dev%2FRShiny%2FTADA%20Module%201%20Mockups%2002252022%2Epdf&viewid=deb12f0b%2D3d2c%2D4694%2Dbe22%2D7d262f785cce&parent=%2Fsites%2FWQPDataAssessmentTeam%2FShared%20Documents%2FGeneral%2FTADA%20Dev%2FRShiny
slide 5: https://usepa.sharepoint.com/:p:/r/sites/WQPDataAssessmentTeam/_layouts/15/Doc.aspx?sourcedoc=%7BD09286FA-0BB1-452B-9920-913CE3C9D772%7D&file=Tool%201%20Mock%20Ups.pptx&action=edit&mobileredirect=true

**Comment by hillarymarler** [comment]
I'm interested in helping with this one if it is still in need of additional development after I finish working on vignettes for upcoming presentations.

**Comment by cristinamullin** [comment]
Adding relevant note from Erik Leppo below (TADA Working Group follow up email): 

I ran across an article today that described some packages that did similar cleaning of coordinates albeit some for a specific purpose.  But a number of the tests the package runs might be useful (missing, outside of study area, 0/0, at sea, political unit centroids, spatial outliers, conversion errors).

Here is the article:  [https://www.r-bloggers.com/2023/01/safe-and-simple-cleaning-of-species-occurrences/](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.r-bloggers.com%2F2023%2F01%2Fsafe-and-simple-cleaning-of-species-occurrences%2F&data=05%7C01%7CMullin.Cristina%40epa.gov%7Cee78619934954fb74f4608daff997ea0%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C638103331967580381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=1HK6BBQwonhbop0WILzWEMXNVZpFgqDvkktxJQaaQWk%3D&reserved=0)

The list of checks is here: [https://ropensci.github.io/CoordinateCleaner/reference/index.html](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fropensci.github.io%2FCoordinateCleaner%2Freference%2Findex.html&data=05%7C01%7CMullin.Cristina%40epa.gov%7Cee78619934954fb74f4608daff997ea0%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C638103331967580381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=irZ25whyqqyRj%2Fgde%2FoE8G2n%2FRXbDs7%2BxBsRzoIa%2FzI%3D&reserved=0)

The vignettes with good demos are here: 
[https://ropensci.github.io/CoordinateCleaner/articles/Cleaning_GBIF_data_with_CoordinateCleaner.html](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fropensci.github.io%2FCoordinateCleaner%2Farticles%2FCleaning_GBIF_data_with_CoordinateCleaner.html&data=05%7C01%7CMullin.Cristina%40epa.gov%7Cee78619934954fb74f4608daff997ea0%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C638103331967580381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qKRdwyZqxP9ubyKqqDRw192wR3bRp8JPZ1uyn0950gY%3D&reserved=0)
[https://ropensci.github.io/CoordinateCleaner/index.html](https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fropensci.github.io%2FCoordinateCleaner%2Findex.html&data=05%7C01%7CMullin.Cristina%40epa.gov%7Cee78619934954fb74f4608daff997ea0%7C88b378b367484867acf976aacbeca6a7%7C0%7C0%7C638103331967580381%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gI4d8CGNhxW33u4GpPVZWs%2FpqFRxZA%2Fr%2FO6N2iaylC8%3D&reserved=0)

You may have already investigated the existing packages out there for coordinate and other data cleaning and this is old news for you.  But if not then this is my small contribution to the project.    The package seems to only do coordinate cleaning and is on CRAN (and ropensci) so it should stay supported and not get orphaned.

**Comment by cristinamullin** [comment]
This issue is being addressed elsewhere: https://github.com/USEPA/TADA/issues/464 and https://github.com/USEPA/TADA/issues/474
