### ISSUE TITLE
Vignetts cannot build if they include TADA_OverviewMap because they cannot find shp files

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#447]
**Describe the bug**

TADA_OverviewMap runs [TADA_addPolys()](https://usepa.github.io/TADA/reference/TADA_addPolys.html) and [TADA_addPoints()](https://usepa.github.io/TADA/reference/TADA_addPoints.html) which both leverage [getLayer()](https://usepa.github.io/TADA/reference/getLayer.html). 

[writeLayer()](https://usepa.github.io/TADA/reference/writeLayer.html) is used to save shp files to the r package, and [TADA_UpdateTribalLayers()](https://usepa.github.io/TADA/reference/TADA_UpdateTribalLayers.html) is used to update those files when needed during routine pkg maintenance. Then getLayer is used to read them within other functions as needed.

This workflow seems to work fine except when building the vignettes. The vignette cannot find the shp files in the R package during the build. This means the maps cannot be shown on the pkgdown site: https://usepa.github.io/TADA/articles/TADAModule1.html

**To Reproduce**

Open TADAModule1 vignette and remove eval = F from the code chunk that include TADA_OverviewMap. 

See error: 
``` r
processing file: TADAModule1.Rmd
  |.                    |   4% [install_remotes]                               trying URL 'http://cran.us.r-project.org/bin/windows/contrib/4.3/remotes_2.5.0.zip'
Content type 'application/zip' length 430165 bytes (420 KB)
==================================================
downloaded 420 KB

                                                                                                                                           

Quitting from lines  at lines 374-375 [Map] (TADAModule1.Rmd)
Error:
! Cannot open "inst/extdata/shapefiles/AKAllotments.shp"; The file doesn't seem to exist.
Backtrace:
  1. TADA::TADA_OverviewMap(TADAProfile)
  6. TADA::TADA_addPolys(...)
  7. TADA::getLayer(layerfilepath, bbox)
  9. sf:::st_read.character(layerfilepath)
 10. sf:::CPL_read_ogr(...)
Execution halted
```

**Expected behavior**

The vignette should be able to find the files and build/knit. There may be a different way to save files to an r package (or read them) so they are discoverable during the vignette build. Maybe they need to be saved to the data folder instead and documented. Or maybe they need to be saved using a different function. We use usethis elsewhere to save ref files and data files to the package, but it is not clear how this process should translate for saving and reading geospatial files in R packages...

**Comment by mhweber** [comment]
Hi @cristinamullin - I think if you just install data in the inst/exdata folder it should work - that's what I do for data packages I make like [this one](https://github.com/mhweber/awra2020spatial/tree/master).  Then you can just explicitly load them using syntax like nc <- system.file("gpkg/nc.gpkg", package="sf"). Another quick thing might be writing to and reading from vignette folder as described [here](https://stackoverflow.com/questions/24867153/vignette-cant-find-data-files-during-devtoolscheck)? Hopefully this might help!
