### ISSUE TITLE
Flag Page Summary Table Generation

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#46]
ALWAYS: Run all site and result flag functions and generate summary table (drafted in mock ups). 

Flag=TRUE: append all flag columns to dataset
Flag=FALSE: do not append all flag columns to dataset

Clean=TRUE: remove all data that has been flagged AND remove flag columns if there
Clean=FALSE: do not remove all data that has been flagged

**Comment by ehinman** [comment]
@cristinamullin Is this still relevant?
