### ISSUE TITLE
RecordSummary

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#51]
Generate record summary. May fit well in Utilities.R folder because it can be used throughout the assessment process. 

This function relies on initial data retrieval generation of a "clean" file and a "raw file"

Summary 
Total Records in Raw File: 544
Total Records Removed: 48
Total Records in Clean File: 496

Total Sites in Raw File: 20
Total Sites Removed: 4
Total Sites in Clean File: 16

**Comment by ehinman** [comment]
@cristinamullin Do you want this to be something someone can run at any time in TADA and it will report out these numbers? I can create a function for this.

**Comment by cristinamullin** [comment]
In order for this to work, would we need to implement the "remove" column populated with TRUE or FALSE in the TADA R Package? I think we need this for consistency with the current Shiny functionality (single file, vs a raw and clean file)?

**Comment by ehinman** [comment]
Very true. Or it could be a function that takes two objects and compares the number of unique records and sites in each.
