### ISSUE TITLE
CensoredDataSummary

### ISSUE THREAD

**Issue by cristinamullin** [USEPA/TADA#61]
Function title: CensoredDataSummary
Some result values are either below or above the detection limit of the equipment used to collect data. Users may want substitute values for this data to make it more useful for assessment. This function will provide  a summary of the censored data in this dataset. 

Always: generate censored data stats table and provide it to function users as a .csv (or in environment?)

Depends on ResultsSpecialChars Function

See summary table here:
https://usepa.sharepoint.com/sites/WQPDataAssessmentTeam/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FWQPDataAssessmentTeam%2FShared%20Documents%2FGeneral%2FTADA%20Dev%2FFirstTool%5FDataDiscoveryandCleaning%2FTemplates%2FDraft%20Templates&viewid=deb12f0b%2D3d2c%2D4694%2Dbe22%2D7d262f785cce

**Comment by cristinamullin** [comment]
@ehinman can this be closed?

**Comment by ehinman** [comment]
Yes, I think so!
