### ISSUE TITLE
Research iterating by row efficiently

### ISSUE THREAD

**Issue by jakegreif** [USEPA/TADA#69]
The current code (rowwise and case_when functions) used to check data row by row is used in a number of functions (command+f in .R files to see which functions use it). But it takes a long time to run, especially for larger datasets. Research other methods of checking data row by row in R and compare the efficiency of those methods to the one being used.

Note that this may be the best way to do it; it could be that the process of looking at data row by row is cumbersome regardless of how it's code.

**Comment by cristinamullin** [comment]
Note: This is used a lot in the Transformations.R file
