### ISSUE TITLE
Non-Boolean argument input checks

### ISSUE THREAD

**Issue by jakegreif** [USEPA/TADA#95]
Double check that all functions have a check upfront for non-Boolean inputs for Boolean arguments. This is an easy, but somewhat tedious task -- make sure that all functions with Boolean arguments have this check prior to executing the function:

(#) check if x is Boolean
if(is.logical(x) == FALSE){ 
stop("x argument must be Boolean (TRUE or FALSE)") 
}

(the WQXTargetUnits function uses the code above)

Some functions have a check at the end, where we use if else functions that work like this: if clean = TRUE, do this; if clean = FALSE, do that; else, stop("clean argument must be Boolean (TRUE or FALSE)"). Remove this code and use the code provided above instead for consistency. I know the if, else logic is present in the InvalidFraction/Speciation/etc. functions, at least.

**Comment by jbousquin** [comment]
Starts to seem like type hinting, R is dynamically typed but I'm curious if R has something built-in to streamline this
